# Generated by Django 3.2.6 on 2021-08-30 16:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=200)),
                ('banned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('wiki', ckeditor.fields.RichTextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keepTrack.user')),
                ('members_p', models.ManyToManyField(related_name='members_p', to='keepTrack.User')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('members_l', models.ManyToManyField(related_name='members_l', to='keepTrack.User')),
                ('project_l', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepTrack.project')),
                ('tags_l', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('time', models.DateTimeField()),
                ('card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='keepTrack.card')),
                ('list', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='keepTrack.list')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepTrack.project')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keepTrack.user')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='list_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepTrack.list'),
        ),
        migrations.AddField(
            model_name='card',
            name='members_c',
            field=models.ManyToManyField(to='keepTrack.User'),
        ),
        migrations.AddField(
            model_name='card',
            name='project_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepTrack.project'),
        ),
        migrations.AddField(
            model_name='card',
            name='tags_c',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
