# Generated by Django 3.2.6 on 2021-10-18 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_c',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsOfCard', to='keepTrack.card'),
        ),
    ]
