# Generated by Django 3.2.6 on 2021-09-01 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_admins',
            field=models.ManyToManyField(related_name='members_p_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
