# Generated by Django 3.2.6 on 2021-09-04 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0002_project_project_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='members_c',
            field=models.ManyToManyField(related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='project_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='keepTrack.project'),
        ),
        migrations.AlterField(
            model_name='list',
            name='members_l',
            field=models.ManyToManyField(related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='members_p',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_admins',
            field=models.ManyToManyField(related_name='project_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
