# Generated by Django 3.2.6 on 2021-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0004_auto_20210905_1110'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('list_name', 'project_l'), name='unique_list'),
        ),
    ]
