# Generated by Django 3.2.6 on 2021-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0005_list_unique_list'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='list',
            name='unique_list',
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('id', 'project_l'), name='unique_list'),
        ),
    ]
