# Generated by Django 3.2.6 on 2021-09-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0006_auto_20210906_1452'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='list',
            name='unique_list',
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('list_name', 'project_l'), name='unique_list'),
        ),
    ]
