# Generated by Django 3.2.6 on 2021-09-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0007_auto_20210906_1453'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='list',
            name='unique_list',
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('list_name', 'project_l')},
        ),
    ]
