# Generated by Django 3.2.6 on 2021-09-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0008_auto_20210906_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set(),
        ),
    ]
