# Generated by Django 3.2.6 on 2021-09-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0009_alter_list_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('list_name', 'project_l')},
        ),
    ]
