# Generated by Django 3.2.6 on 2021-10-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0011_alter_card_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='project_l',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listsOfProject', to='keepTrack.project'),
        ),
    ]
