# Generated by Django 3.2.6 on 2021-10-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0012_alter_list_project_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='list_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardsOfList', to='keepTrack.list'),
        ),
    ]
