# Generated by Django 3.2.6 on 2021-10-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0013_alter_card_list_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='members_l',
        ),
    ]
