# Generated by Django 3.2.6 on 2021-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0014_remove_list_members_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='start_date',
            field=models.DateField(),
        ),
    ]
