# Generated by Django 3.2.6 on 2021-10-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0015_auto_20211004_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['list_name']},
        ),
        migrations.RemoveField(
            model_name='list',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='start_date',
        ),
    ]
