# Generated by Django 3.2.6 on 2021-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepTrack', '0016_auto_20211004_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateField(),
        ),
    ]
